@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(bc, "Blockchain")
System_Ext(ma, "Mobile Application")
System_Ext(pa, "Public Administrator / Service Provider")

Boundary(backend, "Server", "Backend System", "", "", "Server that handles data transfer between systems.") {
  ' Component(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
    Component(RH, "Request Handler") 
    Component(challenger, "Challenge Generator") 
    Component(ext_api, "External API", "", "Provide PAs the API for communication with internal system.") 
    Component(resolver, "DID Resolver", "", "Resolves users DID to correct Public Key in blockchain.") 
    Component(DB, "Database", "PostgreSQL", "Stores revoked keys.") 

    Rel(RH, challenger, "generates a challenge using")
    Rel(ext_api, RH, "redirects data to")
    Rel_U(pa,ext_api, "communicates with")
    Rel(RH, ma, "communication with")
    Rel_U(RH, DB, "checks for revoked keys from")
    Rel_R(RH, resolver, "requests public key from")
    Rel(resolver, bc, "queries for correct blockchain piece")
}

SHOW_LEGEND()

@endpuml
