@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(bc, "Blockchain")
System_Ext(ma, "Mobile Application")
System_Ext(pa, "Public Administrator / Service Provider")
System_Ext(lb, "Load Balancer")

Boundary(backend, "Server", "Backend System", "", "", "Server that handles data transfer between systems.") {
  ' Component(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
    Component(RH, "Request Handler") 
    Component(challenger, "Challenge Generator") 
    Component(ext_api, "External API", "", "Provide PAs the API for communication with internal system.") 
    Component(resolver, "DID Resolver", "", "Resolves users DID to correct Public Key in blockchain.") 
    Component(DB, "Database", "PostgreSQL", "Stores revoked keys and audit logs.") 
    Component(at, "Audit Logger", "", "Handles the read and write operations of audit logging data for transactions.") 

    Rel(RH, challenger, "generates a challenge using")
    Rel(at, RH, "collects and parses logs through")
    Rel(ext_api, RH, "redirects data to")
    Rel_U(pa, lb, "connects with")
    Rel_U(lb, ext_api, "routes to server instance")
    Rel(RH, ma, "communication with")
    Rel_U(RH, DB, "checks for revoked keys from")
    Rel_R(RH, resolver, "requests public key from")
    Rel(resolver, bc, "queries for correct blockchain piece")
}

SHOW_LEGEND()

@endpuml
