@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Boundary(backend, "Backend server", "Backend System", "", "", "Server that handles data transfer between devices and other services") {
    
    Component(RH, "Request Handler") 
    Component(Backend_API, "Other services API handler") 
    Component(Blockchain, "Blockchain")
    Component(Biometric_AI, "User authentication API handler")  
    Component(eID, "User blockchain information") 
    Component(DB, "Database") 

    Rel(RH, Backend_API, "Sends authentication comfirmation")
    Rel_L(Backend_API, RH, "Asks authentication")
    Rel(Blockchain, eID, "holds")
    Rel(RH, Biometric_AI, "Asks Biometric authentication")
    Rel(Biometric_AI, RH, "allows or denies access")
    Rel_R(RH, DB, "Asks database for user's blockchain identification information")
    Rel(DB, RH, "Returns query")
    Rel(DB, Blockchain, "Queries for correct blockchain piece")
    Rel(Blockchain, DB, "User's blockchain identification information")
}

SHOW_LEGEND()

@endpuml
