@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!NO_LAY_ROTATE=1

' User(s) of the system
' Person(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
Person(citizens, "Citizen", "People of Finland")
Person(maintainer, "System Maintainer", "Handles Production Development and Maintenance")

' The Ext Systems
' System_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type, ?baseShape)
System_Ext(blockchain, "Blockchain", "")
System_Ext(phone_dev, "Phone Device", "Users own mobile phone")
System_Ext(suomifi, "Suomi.fi", "National strong authentication service handler")

' Boundary(alias, label, ?type, ?tags, ?link, ?descr)
Boundary(useless_auth, "SSI/SSO Face-ID Authentication", "Software System", "", "", "System that can provide a strong authentication based on Face Recognition in decentralized manner by utilizing blockchain with AI.") {
    Container(backend, "Server", "JSON/HTTPS", "Handles database access for users and makes API calls to external systems.")
    Container(phoneapp, "Phone Application", "HTTPS", "Runs on users mobile phone device")
    Container(database, "Database", "", "Holds users blockchains first node. ")
    
    Rel(backend, phoneapp, "Handles challenges and authentication to users phones")
    Rel(backend, database, "Stores linking information to")
}

' Rel($from, $to, $label, $techn="", $descr="", $sprite="", $tags="", $link="", $index="", $rel="")
Rel(maintainer, backend, "Maintains")
Rel(citizens, phone_dev, "Has a")
Rel(phone_dev, backend, "Connects to", "")
Rel(backend, suomifi, "Provides the users' eID to")
Rel(backend, blockchain, "Checks users")

SHOW_LEGEND()

@enduml

